#!/usr/bin/env python3
"""Log in to the Forward UI via agent-browser and export the session cookies.

Useful when another script or tool needs to hit a Forward endpoint that
requires a web-session cookie (not the API key). Typical downstream use:

    export_session.py --format cookie-header > /tmp/cookie.txt
    curl -H "Cookie: $(cat /tmp/cookie.txt)" "$FORWARD_API_BASE_URL/some/ui/endpoint"

Requires ``agent-browser`` on PATH and a one-time vault save to populate it:

    read -s FWD_PASS && agent-browser auth save forward \\
        --url "$FORWARD_API_BASE_URL" \\
        --username "<user>" \\
        --password-stdin <<< "$FWD_PASS" && unset FWD_PASS

The daemon persists, so repeated ``auth login forward`` calls are cheap
(browser state reused).

Output formats (``--format``):

  - ``json`` (default): the full filtered cookie list + metadata
  - ``cookie-header``: a ``name1=val1; name2=val2`` string suitable for an
    HTTP ``Cookie:`` header
  - ``netscape``: a Netscape-format cookie jar usable by ``curl --cookie``

Filters cookies by the Forward host derived from ``FORWARD_API_BASE_URL``
(or overridden with ``--host``).
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _bootstrap  # noqa: F401 — unused here, but keeps the skill's shape consistent

from forward_client import die  # reuse the consistent error helper


def derive_host(base_url: str | None) -> str:
    if not base_url:
        die("FORWARD_API_BASE_URL is not set; pass --host explicitly.")
    parsed = urlparse(base_url)
    host = parsed.netloc or parsed.path
    if not host:
        die(f"cannot derive host from FORWARD_API_BASE_URL={base_url!r}")
    return host


def default_allowed(host: str) -> str:
    return f"{host},*.{host}"


def run_ab(args: list[str]) -> tuple[int, str, str]:
    """Run an agent-browser command. Return (returncode, stdout, stderr)."""
    try:
        proc = subprocess.run(
            ["agent-browser", *args],
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError:
        die("agent-browser not found on PATH. See SKILL.md Prerequisites.")
    return proc.returncode, proc.stdout, proc.stderr


def host_matches(cookie_domain: str, target_host: str) -> bool:
    """True if a cookie with domain=cookie_domain would be sent to target_host."""
    if not cookie_domain:
        return False
    cd = cookie_domain.lstrip(".").lower()
    th = target_host.lower()
    return th == cd or th.endswith("." + cd)


def format_cookie_header(cookies: list[dict]) -> str:
    return "; ".join(f"{c['name']}={c.get('value', '')}" for c in cookies if c.get("name"))


def format_netscape(cookies: list[dict]) -> str:
    """Netscape cookie jar format (curl --cookie).

    Columns: domain, flag(TRUE/FALSE), path, secure, expires, name, value.
    """
    lines = [
        "# Netscape HTTP Cookie File",
        "# https://curl.se/docs/http-cookies.html",
        "# Generated by forward-ui/export_session.py",
    ]
    for c in cookies:
        domain = c.get("domain", "")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = str(int(c.get("expires", 0) or 0))
        name = c.get("name", "")
        value = c.get("value", "")
        if not name:
            continue
        lines.append("\t".join([domain, flag, path, secure, expires, name, value]))
    return "\n".join(lines) + "\n"


def main() -> int:
    p = argparse.ArgumentParser(
        description="Log in to Forward UI via agent-browser and emit session cookies",
    )
    p.add_argument(
        "--vault-entry", default="forward",
        help="agent-browser auth vault entry to use (default 'forward')",
    )
    p.add_argument(
        "--host",
        help="Forward host (default: parse from FORWARD_API_BASE_URL)",
    )
    p.add_argument(
        "--allowed-domains",
        help="Comma-separated allowlist passed to agent-browser. "
             "Default: $FORWARD_UI_ALLOWED_DOMAINS or '<host>,*.<host>'",
    )
    p.add_argument(
        "--format", choices=("json", "cookie-header", "netscape"), default="json",
        help="Output format (default json)",
    )
    p.add_argument(
        "--skip-login", action="store_true",
        help="Do not run 'auth login'; assume a warm session exists",
    )
    args = p.parse_args()

    base_url = os.environ.get("FORWARD_API_BASE_URL", "")
    host = args.host or derive_host(base_url)
    allowed = (
        args.allowed_domains
        or os.environ.get("FORWARD_UI_ALLOWED_DOMAINS")
        or default_allowed(host)
    )

    # 1. Log in (vault drives the form — LLM never sees the password)
    if not args.skip_login:
        rc, out, err = run_ab([
            "--allowed-domains", allowed,
            "auth", "login", args.vault_entry,
        ])
        if rc != 0:
            die(f"auth login failed (rc={rc}): {err.strip() or out.strip()}")

    # 2. Dump cookies as JSON
    rc, out, err = run_ab(["--json", "--allowed-domains", allowed, "cookies"])
    if rc != 0:
        die(f"cookies fetch failed (rc={rc}): {err.strip() or out.strip()}")

    try:
        parsed: Any = json.loads(out) if out.strip() else []
    except json.JSONDecodeError as e:
        die(f"agent-browser cookies output was not JSON: {e}")

    # agent-browser may emit either a bare list or {"cookies": [...]}. Tolerate both.
    if isinstance(parsed, dict):
        cookies = parsed.get("cookies") or parsed.get("items") or []
    elif isinstance(parsed, list):
        cookies = parsed
    else:
        die(f"unexpected cookies payload shape: {type(parsed).__name__}")

    filtered = [
        c for c in cookies
        if isinstance(c, dict) and host_matches(c.get("domain", ""), host)
    ]

    if not filtered:
        print(f"# no cookies matched host={host!r} (raw cookie count: {len(cookies)})",
              file=sys.stderr)

    if args.format == "json":
        json.dump({
            "baseUrl": base_url,
            "host": host,
            "count": len(filtered),
            "cookies": filtered,
            "cookieHeader": format_cookie_header(filtered),
        }, sys.stdout, indent=2, default=str)
        sys.stdout.write("\n")
    elif args.format == "cookie-header":
        sys.stdout.write(format_cookie_header(filtered) + "\n")
    elif args.format == "netscape":
        sys.stdout.write(format_netscape(filtered))
    return 0


if __name__ == "__main__":
    sys.exit(main())
